layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - temp
    # - personal-website
    # - graduation

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: satwork13
  keybase: satwork13
  linkedin: skonapur
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: satwork13
  # unsplash: your_username
  # vk: your_username
  # tryhackme: https://tryhackme.com/p/satwork13

topics:
  - name: Tryhackme
    web_url: https://tryhackme.com/p/satwork13
    image_url: https://iili.io/JOLOzJ.png

  - name: Pentesterlab
    web_url: https://pentesterlab.com/profile/skonapur
    image_url: https://iili.io/JOL1iQ.png

  - name: Hackthebox
    web_url: https://www.hackthebox.eu/profile/333055
    image_url: https://secure.meetupstatic.com/photos/event/a/c/9/e/600_486584190.jpeg